import type { Question } from '@/types';

/**
 * All 40 questions. See docs/03-question-bank.md.
 * Self-assessment options (SA) are in ascending score order.
 * Scenario options (SC) are in the fixed shuffled render order given in the source.
 * NOTE: render order is intentionally not score order. Do not sort.
 */
export const QUESTIONS: readonly Question[] = [
  // ---- Part A: self-assessment (SA01-SA30) ----
  {
    id: 'SA01', kind: 'self', competency: 'complexity-translation',
    fa: 'وقتی یک بریف پیچیده به دستت می‌رسد، کارت معمولاً از کجا شروع می‌شود؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Component & Task Clarity"',
        fa: 'عناصر پیچیده را در بریف پیدا می‌کنم و با الگوهای استاندارد UI بار ذهنی کاربر را کم می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Flow & Logic Simplification"',
        fa: 'منطق پنهان محصول، مثل نحوه‌ی محاسبه‌ها یا استثناها، را به بازخورد بصری و زبان ساده ترجمه می‌کنم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Experience Orchestration"',
        fa: 'کل روایت را در طول یک مسیر end-to-end می‌چینم تا feature های فنی به مدل ذهنی کاربر وصل شوند.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Cross-Vertical Architecture" / Lead "Quality & Craft Mentorship"',
        fa: 'framework می‌سازم تا مدل ذهنی واحد در چند محصول حفظ شود، یا استاندارد شفافیت را برای کل تیم تعریف می‌کنم.' },
    ],
  },
  {
    id: 'SA02', kind: 'self', competency: 'complexity-translation',
    fa: 'ساختار اطلاعات یک بخش تازه را چطور تعیین می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, extended facet',
        fa: 'از ساختار و naming موجود محصول پیروی می‌کنم و همان الگو را ادامه می‌دهم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, extended facet',
        fa: 'وقتی می‌بینم دسته‌بندی فعلی جواب نمی‌دهد، ساختار را بازچینی می‌کنم و دلیلش را مستند می‌کنم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, extended facet',
        fa: 'information architecture را پیش از طراحی هر screen ای با روش‌هایی مثل Tree Test می‌سنجم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff, extended facet',
        fa: 'یک IA مرجع برای کل پلتفرم تعریف می‌کنم که تیم‌های دیگر رویش بنا کنند.' },
    ],
  },
  {
    id: 'SA03', kind: 'self', competency: 'problem-definition',
    fa: 'وقتی یک درخواست مشخص از سمت Product می‌آید، مثلاً «این دکمه را اضافه کن»، چه می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Goal Clarity"',
        fa: 'هدف اصلی و کاربر هدف آن task را می‌پرسم تا مطمئن شوم درست فهمیده‌ام.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Assumption Testing"',
        fa: 'زیر لایه‌ی درخواست را می‌کاوم تا محدودیت پنهان یا هدف متناقض پیدا کنم، و تا شفاف نشدن مسئله وارد high-fidelity نمی‌شوم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Framing & Scoping"',
        fa: 'یک Problem Statement می‌نویسم که squad را هم‌سو کند و جلوی scope creep را بگیرد.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Meta-Problem Identification" / Lead "Methodological Framing"',
        fa: 'همان اصطکاک را در چند محصول دنبال می‌کنم و مسئله را در سطح ساختار تجربه تعریف می‌کنم، یا به تیم یاد می‌دهم چطور بریف ضعیف را پس بزند.' },
    ],
  },
  {
    id: 'SA04', kind: 'self', competency: 'problem-definition',
    fa: 'نسبتت با چارچوب‌های تعریف مسئله مثل 5 Whys یا Jobs to be Done چیست؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'وقتی کسی پیشنهاد بدهد از آن‌ها استفاده می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'خودم تشخیص می‌دهم کدام چارچوب به این مسئله می‌خورد و به کارش می‌برم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'برای پروژه‌های بزرگ چارچوب را انتخاب می‌کنم و خروجی‌اش را برای تیم مستند می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "Methodological Framing"',
        fa: 'چارچوب تعریف مسئله را در تیم جا می‌اندازم و روی مسائل چندمحصولی به کارش می‌برم.' },
    ],
  },
  {
    id: 'SA05', kind: 'self', competency: 'strategic-alignment',
    fa: 'رابطه‌ی کارت با اهداف بیرون از تیم را چطور توصیف می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Contextual Awareness"',
        fa: 'می‌دانم task ام به هدف فوری squad چه ربطی دارد و می‌توانم توضیحش بدهم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Cross-Functional Coordination"',
        fa: 'زودتر از موعد با Engineering و Product هماهنگ می‌کنم تا طرح در همین sprint شدنی باشد.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Roadmap Influence"',
        fa: 'با stakeholder های ارشد رابطه می‌سازم و با design روی roadmap اثر می‌گذارم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Domain Synthesis" / Lead "Operational Alignment"',
        fa: 'چند squad یا خط محصول را حول یک مسیر استراتژیک واحد هم‌سو می‌کنم، یا فرایندهای تیم را با سرعت و محدودیت‌های شرکت تنظیم می‌کنم.' },
    ],
  },
  {
    id: 'SA06', kind: 'self', competency: 'strategic-alignment',
    fa: 'در گفت‌وگو با بیزنس معمولاً کجای میز نشسته‌ای؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'KPI هایی که کارم رویشان اثر دارد را می‌شناسم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'طرحم را با زبان trade-off فنی و زمانی دفاع می‌کنم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Vision Prototype"',
        fa: 'با prototype و روایت، تصمیم stakeholder را جابه‌جا می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "Operational Alignment"',
        fa: 'به بقیه یاد می‌دهم چطور به زبان بیزنس حرف بزنند و کارشان را به سود و نگه‌داشت کاربر وصل کنند.' },
    ],
  },
  {
    id: 'SA07', kind: 'self', competency: 'product-thinking',
    fa: 'نگاهت به محصولی که رویش کار می‌کنی چقدر عمیق است؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "User Intent & Journey"',
        fa: 'value proposition محصول را می‌فهمم و می‌توانم مسیر کاربر از ورود تا خرید را ترسیم کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Business Value & Mechanics"',
        fa: 'می‌دانم محصول از کجا درآمد دارد و feature را طوری طراحی می‌کنم که این اهرم‌ها بدون آسیب به UX بهتر شوند.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Vertical Market Fit"',
        fa: 'شریک واقعی PM هستم، رقبا را می‌شناسم و شکاف‌های محصولی قابل پر شدن را پیدا می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff, "Ecosystem Thinking"',
        fa: 'تعامل همه‌ی خطوط محصول را می‌بینم و framework هایی می‌سازم که cross-selling و LTV را در کل پلتفرم بالا ببرد.' },
    ],
  },
  {
    id: 'SA08', kind: 'self', competency: 'product-thinking',
    fa: 'وقتی طرح تو با هدف کوتاه‌مدت بیزنس تعارض پیدا می‌کند؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'تعارض را به PM می‌گویم و منتظر تصمیم او می‌مانم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'یک گزینه‌ی میانه پیشنهاد می‌دهم که هر دو طرف را تا حدی راضی کند.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'هزینه‌ی هر طرف را با داده تخمین می‌زنم و پیشنهادم را روی همان بنا می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff, adjacent to solution-accountability "Business Model Integrity"',
        fa: 'مسئله را به مدل کسب‌وکار برمی‌گردانم و نشان می‌دهم کدام انتخاب در بلندمدت ارزش بیشتری می‌سازد.' },
    ],
  },
  {
    id: 'SA09', kind: 'self', competency: 'evidence-based-design',
    fa: 'نسبتت با طرح خودت چیست؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Humility & Inquiry"',
        fa: 'می‌دانم طرحم یک فرضیه است نه پاسخ نهایی، و دنبال چراییِ رفتار کاربر می‌گردم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Pattern Recognition & Triangulation"',
        fa: 'سیگنال‌های مختلف را به هم وصل می‌کنم تا جهت طراحی محکم‌تری بسازم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Risk Mitigation"',
        fa: 'شواهد را طوری می‌سازم که جلوی اشتباه‌های پرهزینه را بگیرد، نه اینکه فقط شواهد موجود را پیدا کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Synthesizing Systemic Truths" / Lead "The Culture of Inquiry"',
        fa: 'حقیقت‌های رفتاری‌ای استخراج می‌کنم که برای همه‌ی محصولات اصل الزام‌آور می‌شوند، یا فرهنگ «از کجا می‌دانیم درست است؟» را در تیم جا می‌اندازم.' },
    ],
  },
  {
    id: 'SA10', kind: 'self', competency: 'evidence-based-design',
    fa: 'وقتی داده با شهودت مخالف است؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'داده را می‌پذیرم و طرح را عوض می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'اول کیفیت و روش جمع‌آوری داده را بررسی می‌کنم و بعد تصمیم می‌گیرم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'یک سنجش کوچک طراحی می‌کنم که مشخصاً همین اختلاف را حل کند.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "The Culture of Inquiry"',
        fa: 'تعارض را به یک بحث روشمند در تیم تبدیل می‌کنم تا معیار مشترکی برای «شاهد قابل قبول» ساخته شود.' },
    ],
  },
  {
    id: 'SA11', kind: 'self', competency: 'discovery-execution',
    fa: 'تحقیق کاربر را در چه سطحی اجرا می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Assisted Execution"',
        fa: 'تست‌های ساده و ارزیابانه مثل 5-second test یا unmoderated usability را اجرا می‌کنم و بدون سوگیری گزارش می‌دهم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Independent Discovery"',
        fa: 'مصاحبه یا usability session را از صفر تا صد خودم برنامه‌ریزی و اجرا می‌کنم و اسکریپت غیرجهت‌دار می‌نویسم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Multi-Method Validation"',
        fa: 'می‌دانم برای هر مسئله کدام روش را انتخاب کنم و آزمایش‌هایی طراحی می‌کنم که با کم‌ترین هزینه بیشترین اطمینان را بدهند.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Behavioral Insights" / Lead "Discovery Enablement"',
        fa: 'با ترکیب روش‌ها رفتارهای عمیق و غیربدیهی را پیدا می‌کنم، یا toolkit تحقیق را می‌سازم تا بقیه سریع‌تر و دقیق‌تر آزمایش کنند.' },
    ],
  },
  {
    id: 'SA12', kind: 'self', competency: 'discovery-execution',
    fa: 'وقتی برای تحقیق وقت کافی نیست؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'بدون تحقیق پیش می‌روم و بعد از انتشار بازخورد جمع می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'کوچک‌ترین نسخه‌ی ممکن از روش را اجرا می‌کنم تا دست‌کم یک سیگنال داشته باشم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'ریسک هر مسیر را می‌سنجم و فقط پرریسک‌ترین فرض را می‌سنجم.' },
      { id: 'd', score: 4, sourceColumn: 'Manager-adjacent, "Democratizing Discovery"; rendered at Lead altitude',
        fa: 'کاری می‌کنم زمان discovery از ابتدا در برنامه‌ریزی پروژه دیده شود، نه اینکه هر بار قربانی deadline شود.' },
    ],
  },
  {
    id: 'SA13', kind: 'self', competency: 'solution-accountability',
    fa: 'بعد از انتشار، چقدر کار را دنبال می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Outcome Awareness"',
        fa: 'عملکرد طرحم را دنبال می‌کنم و می‌توانم بگویم هدف فوری محقق شده یا نه.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Performance Monitoring"',
        fa: 'در مرحله‌ی طراحی success signal تعریف می‌کنم و خودم عملکرد را ممیزی می‌کنم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Post-Launch Iteration Strategy"',
        fa: 'سلامت کل یک خط محصول را برمی‌دارم و تیم را در چرخه‌های build-measure-learn جلو می‌برم تا KPI برسد.' },
      { id: 'd', score: 4, sourceColumn: 'Staff, "Ecosystem Health"',
        fa: 'پاسخ‌گوی متریک‌هایی هستم که چند محصول را در بر می‌گیرد و می‌بینم کجا بهینه‌سازی محلی به تجربه‌ی کلی ضربه می‌زند.' },
    ],
  },
  {
    id: 'SA14', kind: 'self', competency: 'solution-accountability',
    fa: 'وقتی طرحت جواب نداده است؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'منتظر می‌مانم تیم تصمیم بگیرد چه کار کنیم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'خودم یک iteration کوچک پیشنهاد می‌دهم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'علت شکست را مستند می‌کنم و آن را وارد تصمیم بعدی تیم می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "Accountability Culture"',
        fa: 'post-mortem را به آیین تیمی تبدیل می‌کنم که در آن اعتراف به شکست امن است.' },
    ],
  },
  {
    id: 'SA15', kind: 'self', competency: 'craftsmanship',
    fa: 'کیفیت اجرای بصری کارت را چطور توصیف می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Visual Fundamentals"',
        fa: 'layout تمیز و متوازن می‌سازم و سلسله‌مراتب بصری و brand guideline را رعایت می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Interaction & Refinement"',
        fa: 'روی micro-interaction و state ها مثل hover و error و active مسلطم و طرح را برای کاربران متنوع در دسترس نگه می‌دارم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Visual Storytelling & Polish"',
        fa: 'زبان بصری محصول و استاندارد فنی آن را خودم تعیین می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Platform-Level Craft Architecture" / Lead "Quality Assurance & Mentorship"',
        fa: 'مسائل بصری پیچیده را در سطح کل اکوسیستم حل می‌کنم، مثل framework دسترس‌پذیری یا کتابخانه‌ی motion، یا آیین critique و visual audit را برای تیم می‌گذارم.' },
    ],
  },
  {
    id: 'SA16', kind: 'self', competency: 'craftsmanship',
    fa: 'متن داخل محصول را چطور می‌نویسی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, extended facet',
        fa: 'متن‌ها را همان‌طور که به دستم می‌رسد استفاده می‌کنم و اگر مبهم بود می‌پرسم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, extended facet',
        fa: 'خودم متن UI را می‌نویسم و بازنویسی می‌کنم تا کوتاه و دقیق و بدون واژه‌ی تخصصی اضافه باشد.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, extended facet',
        fa: 'برای محصول لحن و الگوی نوشتاری تعریف می‌کنم و error و empty state ها را با همان الگو می‌نویسم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, derived from "Jargon-Busting" and the Plain Language Policy',
        fa: 'استاندارد زبان محصول را در سطح سازمان جا می‌اندازم و سرش با تیم‌های حقوقی یا محتوا مذاکره می‌کنم.' },
    ],
  },
  {
    id: 'SA17', kind: 'self', competency: 'system-stewardship',
    fa: 'نسبتت با Design System چیست؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Component Adoption"',
        fa: 'از library صد در صد درست استفاده می‌کنم و component های ناقص یا خراب را گزارش می‌دهم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Component Creation & Docs"',
        fa: 'شکاف‌های library را پیدا می‌کنم و component تازه‌ی قابل استفاده‌ی مجدد با مستندات می‌سازم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "System Evolution & Governance"',
        fa: 'استراتژی رشد سیستم را جلو می‌برم تا منظم و قابل اتکا و مقیاس‌پذیر بماند.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Code-to-Design Synchronization" / Lead "System Adoption & Training"',
        fa: 'با Engineering یک single source of truth می‌سازم که Figma و code دقیقاً هم‌تراز باشند، یا تیم را روی استفاده‌ی درست از سیستم آموزش می‌دهم.' },
    ],
  },
  {
    id: 'SA18', kind: 'self', competency: 'system-stewardship',
    fa: 'وقتی component موجود جواب نیازت را نمی‌دهد؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, the negative of "without detaching instances"',
        fa: 'instance را detach می‌کنم و نسخه‌ی سفارشی می‌سازم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'اول با صاحب سیستم چک می‌کنم و اگر لازم بود درخواست تغییر ثبت می‌کنم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "System Evolution & Governance"',
        fa: 'تصمیم می‌گیرم این یک استثنا است یا الگویی تکرارشونده، و بر همان اساس سیستم را عوض می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "System Adoption & Training"',
        fa: 'قاعده‌ی روشنی می‌گذارم که تیم بداند کِی حق دارد از سیستم خارج شود و کِی نه.' },
    ],
  },
  {
    id: 'SA19', kind: 'self', competency: 'shipping-design',
    fa: 'تحویل کار به Engineering در تیم تو چه شکلی است؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "File Hygiene"',
        fa: 'فایل مرتب و named و ساختارمند تحویل می‌دهم و استاندارد layer و page تیم را رعایت می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "State Documentation"',
        fa: 'همه‌ی edge case ها را مستند می‌کنم: error و loading و empty state.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Implementation QA"',
        fa: 'در حین build کنار مهندس‌ها می‌مانم و محصول کدشده را با هدف طراحی تطبیق می‌دهم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Handoff Systems" / Lead "Execution Workflow"',
        fa: 'پل فنی بین design و code را می‌سازم، مثلاً Variables که یک‌به‌یک به token های CSS بخورد، یا استاندارد handoff تیم را تعریف می‌کنم.' },
    ],
  },
  {
    id: 'SA20', kind: 'self', competency: 'shipping-design',
    fa: 'وقتی نسخه‌ی live با طرح فرق دارد؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'مورد را گزارش می‌دهم و منتظر اصلاح می‌مانم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'لیست تفاوت‌ها را با اولویت به مهندس می‌دهم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Design Scrub"',
        fa: 'با ابزار inspect خودم علت را پیدا می‌کنم و راه‌حل قابل اجرا پیشنهاد می‌دهم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "Execution Workflow"',
        fa: 'کاری می‌کنم این اختلاف ساختاری حل شود تا دفعه‌ی بعد اصلاً پیش نیاید.' },
    ],
  },
  {
    id: 'SA21', kind: 'self', competency: 'technical-velocity',
    fa: 'AI کجای کارت نشسته است؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "AI Assistance"',
        fa: 'برای کارهای پایه استفاده می‌کنم: خلاصه کردن مصاحبه یا تولید متن اولیه به جای Lorem Ipsum.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Integration & Synthesis"',
        fa: 'در جریان روزانه‌ام جا داده‌ام: thematic analysis روی داده‌ها و ساخت سریع چند concept تعاملی.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Methodology Acceleration"',
        fa: 'چرخه‌ی کامل آزمایش را با AI هماهنگ می‌کنم، از تحلیل حجم زیاد داده تا prototype منطق‌دار برای اعتبارسنجی.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Custom Workflows" / Lead "Strategy & Governance"',
        fa: 'workflow یا ابزار داخلی می‌سازم که مسیر research-to-design تیم را نیمه‌خودکار کند، یا قاعده‌ی استفاده‌ی مسئولانه از AI را برای تیم تعریف می‌کنم.' },
    ],
  },
  {
    id: 'SA22', kind: 'self', competency: 'technical-velocity',
    fa: 'نسبتت با code چیست؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'محدودیت‌های فنی را از مهندس‌ها می‌پرسم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'HTML و CSS را در حدی می‌فهمم که بدانم چه چیزی گران است.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Vibe Coding"',
        fa: 'خودم prototype کارکردنی می‌سازم تا تصمیم را زودتر بسنجم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff, "Platform Performance Architecture" from shipping-design',
        fa: 'تصمیم‌های طراحی را با اثرشان روی performance و مقیاس‌پذیری پلتفرم می‌سنجم.' },
    ],
  },
  {
    id: 'SA23', kind: 'self', competency: 'chapter-contribution',
    fa: 'بیرون از پروژه‌هایت، نقشت در تیم چیست؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Ritual Participation"',
        fa: 'در آیین‌های تیم شرکت می‌کنم و ماهی دست‌کم یک منبع یا نکته در فضای مشترک می‌گذارم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Process Improvement"',
        fa: 'یک نقطه‌ی اصطکاک در نحوه‌ی همکاری تیم را پیدا می‌کنم و راه بهتری پیشنهاد می‌دهم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Standard Setting"',
        fa: 'استانداردهای داخلی را می‌سازم و پایگاه دانش تیم را به‌روز نگه می‌دارم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Systemic Culture & Ritual Architecture" / Lead "Chapter Health & Ritual Governance"',
        fa: 'چارچوب‌های اجتماعی و عملیاتی طراحی می‌کنم که هوش جمعی تیم را بالا ببرد، یا سلامت و امنیت روانی آیین‌های تیم را تضمین می‌کنم.' },
    ],
  },
  {
    id: 'SA24', kind: 'self', competency: 'chapter-contribution',
    fa: 'وقتی فرایند تیم کند یا ناکارآمد است؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'خودم را با فرایند تطبیق می‌دهم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'مشکل را در retro مطرح می‌کنم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'یک جایگزین مشخص پیشنهاد می‌دهم و اجرای آزمایشی‌اش را جلو می‌برم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead',
        fa: 'مسئولیت طراحی و جا انداختن فرایند جدید را در کل تیم برمی‌دارم.' },
    ],
  },
  {
    id: 'SA25', kind: 'self', competency: 'learning-growth',
    fa: 'یادگیری‌ات چطور جلو می‌رود؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Skill Gap Identification"',
        fa: 'فعالانه بازخورد می‌گیرم و برای یک مهارت فنی مشخص برنامه‌ی بهبود دارم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Domain Mastery"',
        fa: 'موضوعی بیرون از طراحی خالص یاد می‌گیرم، مثل تحلیل داده، تا کارم دقیق‌تر شود.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Cross-Disciplinary Learning"',
        fa: 'دانشم را با تیم به اشتراک می‌گذارم و مهارت‌های لازم آینده را زودتر برمی‌دارم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Deep Domain Expertise" / Lead "Curriculum Design"',
        fa: 'در یک حوزه به مرجع تیم تبدیل شده‌ام، یا برای شکاف‌های مهارتی کل تیم مسیر یادگیری طراحی می‌کنم.' },
    ],
  },
  {
    id: 'SA26', kind: 'self', competency: 'learning-growth',
    fa: 'وقتی با چیزی روبه‌رو می‌شوی که بلد نیستی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'از کسی که بلد است می‌پرسم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'خودم می‌روم یاد می‌گیرم و بعد سراغ کار می‌آیم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'هم‌زمان با یاد گرفتن کار را جلو می‌برم و ریسک ندانستنم را مدیریت می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead',
        fa: 'آنچه یاد گرفته‌ام را به شکل قابل استفاده برای بقیه درمی‌آورم.' },
    ],
  },
  {
    id: 'SA27', kind: 'self', competency: 'adaptability',
    fa: 'واکنشت به تغییر ناگهانی اولویت‌ها چیست؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Task Resilience"',
        fa: 'بین موضوع‌ها جابه‌جا می‌شوم بدون اینکه کیفیت کارم بیفتد.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Handling Ambiguity"',
        fa: 'با بریف ۶۰ درصدی هم شروع می‌کنم و مسیر را در حین کار پیدا می‌کنم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Pivot Leadership"',
        fa: 'در تغییرهای بزرگ نقطه‌ی ثبات تیم هستم و آن‌ها را از تغییر عبور می‌دهم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Scenario Architecture" / Lead "Team Resilience & Safety"',
        fa: 'سیستم‌ها را طوری می‌سازم که ذاتاً انعطاف‌پذیر باشند و چند سناریوی آینده را تاب بیاورند، یا تیم را از شوک تغییرهای پی‌درپی محافظت می‌کنم.' },
    ],
  },
  {
    id: 'SA28', kind: 'self', competency: 'adaptability',
    fa: 'وقتی جهت پروژه وسط کار عوض می‌شود؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'کار جدید را شروع می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'می‌پرسم چه بخشی از کار قبلی هنوز معتبر است و همان را برمی‌دارم.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'هزینه‌ی تغییر را شفاف می‌کنم و مسیر جدید را با کم‌ترین دورریز طراحی می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "Team Resilience & Safety"',
        fa: 'تصمیم می‌گیرم چه چیزی باید همین حالا عوض شود و چه چیزی باید ثابت بماند تا تیم دچار whiplash نشود.' },
    ],
  },
  {
    id: 'SA29', kind: 'self', competency: 'mentorship',
    fa: 'دانشت چطور به بقیه منتقل می‌شود؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Peer Sharing"',
        fa: 'دانسته‌های عملی‌ام را با هم‌تیمی‌ها به اشتراک می‌گذارم تا وقتشان تلف نشود.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Constructive Critique"',
        fa: 'در design review بازخوردی می‌دهم که فقط مشکل را نشان ندهد، راه‌حل را هم یاد بدهد.' },
      { id: 'c', score: 3, sourceColumn: 'Senior, "Direct Mentoring"',
        fa: 'یک یا چند طراح junior را زیر بال می‌گیرم و روی هدف‌های رشدشان کار می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Staff "Craft Masterclasses" / Lead "Career Pathing"',
        fa: 'برای کل تیم جلسه‌های عمیق مهارتی می‌گذارم که سطح همه، حتی senior ها، را بالا ببرد، یا مسیر شغلی افراد را فعالانه مدیریت می‌کنم.' },
    ],
  },
  {
    id: 'SA30', kind: 'self', competency: 'mentorship',
    fa: 'وقتی کار یک نفر در تیم پایین‌تر از استاندارد است؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'خودم درستش می‌کنم.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level',
        fa: 'به او می‌گویم کجا اشکال دارد.' },
      { id: 'c', score: 3, sourceColumn: 'Senior',
        fa: 'با او می‌نشینم تا خودش دلیل و راه‌حل را پیدا کند.' },
      { id: 'd', score: 4, sourceColumn: 'Lead',
        fa: 'الگوی تکرارشونده را می‌بینم و آن را با آموزش یا تغییر فرایند در سطح تیم حل می‌کنم.' },
    ],
  },

  // ---- Part B: scenario questions (SC01-SC10) ----
  // Options are deliberately not in score order. Do not sort.
  {
    id: 'SC01', kind: 'scenario', competency: 'complexity-translation',
    fa: 'یک flow پرداخت چندمرحله‌ای دارید و کاربران در مرحله‌ی آخر رها می‌کنند. تیم حقوقی اصرار دارد متن کامل شرایط در همان صفحه بماند. چه می‌کنی؟',
    options: [
      { id: 'a', score: 2, sourceColumn: 'Mid-Level, "Flow & Logic Simplification"',
        fa: 'متن را در یک accordion جمع می‌کنم و خلاصه‌ی سه‌خطی بالایش می‌گذارم.' },
      { id: 'b', score: 4, sourceColumn: 'Lead, "Quality & Craft Mentorship" and the Plain Language Policy',
        fa: 'با تیم حقوقی می‌نشینم تا معیار مشترکی برای «متن قابل فهم» تعریف کنیم و آن را به قاعده‌ی همه‌ی صفحه‌ها تبدیل کنم.' },
      { id: 'c', score: 1, sourceColumn: 'Junior, "Component & Task Clarity"',
        fa: 'متن را با تایپوگرافی بهتر خواناتر می‌کنم و از تیم حقوقی می‌خواهم اگر می‌شود کوتاهش کند.' },
      { id: 'd', score: 3, sourceColumn: 'Senior, "Experience Orchestration"',
        fa: 'کل مسیر را بازمی‌چینم تا شرایط در همان لحظه‌ای دیده شود که به تصمیم کاربر مربوط است، نه یک‌جا در آخر.' },
    ],
  },
  {
    id: 'SC02', kind: 'scenario', competency: 'problem-definition',
    fa: 'PM می‌گوید «نرخ استفاده از فیلتر پایین است، بیایید فیلتر را برجسته‌تر کنیم.» اولین کارت چیست؟',
    options: [
      { id: 'a', score: 3, sourceColumn: 'Senior, "Framing & Scoping"',
        fa: 'پیش از هر طراحی یک Problem Statement می‌نویسم و با PM سرش توافق می‌کنم که مسئله دیده نشدن است یا بی‌فایده بودن.' },
      { id: 'b', score: 1, sourceColumn: 'Junior, "Goal Clarity" not yet applied',
        fa: 'فیلتر را برجسته‌تر می‌کنم و نتیجه را بعد از انتشار می‌بینم.' },
      { id: 'c', score: 4, sourceColumn: 'Staff, "Meta-Problem Identification"',
        fa: 'همین الگو را در بخش‌های دیگر محصول هم می‌بینم و مسئله را در سطح ساختار جست‌وجو تعریف می‌کنم.' },
      { id: 'd', score: 2, sourceColumn: 'Mid-Level, "Assumption Testing"',
        fa: 'اول داده‌ی رفتاری را نگاه می‌کنم تا بفهمم کاربران فیلتر را نمی‌بینند یا می‌بینند و رهایش می‌کنند.' },
    ],
  },
  {
    id: 'SC03', kind: 'scenario', competency: 'strategic-alignment',
    fa: 'دو squad هم‌زمان دو الگوی متفاوت برای یک تعامل مشابه طراحی کرده‌اند و هر دو تا sprint بعد deadline دارند. چه می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior, "Contextual Awareness"',
        fa: 'الگوی squad خودم را جلو می‌برم و موضوع را به لید گزارش می‌دهم.' },
      { id: 'b', score: 4, sourceColumn: 'Staff, "Domain Synthesis"',
        fa: 'یک تصمیم مشترک بین دو squad می‌گیرم و مسیر واحدی تعریف می‌کنم که هر دو رویش بمانند.' },
      { id: 'c', score: 2, sourceColumn: 'Mid-Level, "Cross-Functional Coordination"',
        fa: 'با طراح squad دیگر هماهنگ می‌کنم تا دست‌کم در این نسخه یکی از دو الگو حذف شود.' },
      { id: 'd', score: 3, sourceColumn: 'Senior, "Roadmap Influence"',
        fa: 'هزینه‌ی واگرایی را برای stakeholder ها قابل دیدن می‌کنم و تصمیم را به سطح درست می‌برم.' },
    ],
  },
  {
    id: 'SC04', kind: 'scenario', competency: 'evidence-based-design',
    fa: 'نتیجه‌ی یک usability test با ۵ کاربر با داده‌ی analytics تناقض دارد. چه می‌کنی؟',
    options: [
      { id: 'a', score: 4, sourceColumn: 'Staff "Synthesizing Systemic Truths" / Lead "The Culture of Inquiry"',
        fa: 'از این تناقض یک اصل مشترک برای تیم می‌سازم که از این به بعد بدانیم کدام سیگنال کجا حجت است.' },
      { id: 'b', score: 2, sourceColumn: 'Mid-Level, "Pattern Recognition & Triangulation"',
        fa: 'هر دو را کنار هم می‌گذارم و دنبال توضیحی می‌گردم که هر دو را پوشش بدهد.' },
      { id: 'c', score: 1, sourceColumn: 'Junior, "Humility & Inquiry" not yet applied',
        fa: 'به داده‌ی analytics تکیه می‌کنم چون حجم نمونه‌اش بیشتر است.' },
      { id: 'd', score: 3, sourceColumn: 'Senior, "Risk Mitigation"',
        fa: 'یک سنجش کوچک طراحی می‌کنم که مشخصاً همین تناقض را حل کند.' },
    ],
  },
  {
    id: 'SC05', kind: 'scenario', competency: 'discovery-execution',
    fa: 'سه هفته تا launch مانده و هیچ تحقیقی روی این feature انجام نشده است. چه می‌کنی؟',
    options: [
      { id: 'a', score: 2, sourceColumn: 'Mid-Level, "Independent Discovery"',
        fa: 'یک unmoderated test کوتاه روی prototype فعلی می‌گیرم.' },
      { id: 'b', score: 3, sourceColumn: 'Senior, "Multi-Method Validation"',
        fa: 'پرریسک‌ترین فرض را جدا می‌کنم و فقط همان را با مناسب‌ترین روش می‌سنجم.' },
      { id: 'c', score: 1, sourceColumn: 'Junior',
        fa: 'launch می‌کنیم و بعد از انتشار بازخورد جمع می‌کنم.' },
      { id: 'd', score: 4, sourceColumn: 'Lead, "Discovery Enablement"',
        fa: 'هم حداقل سنجش را همین حالا اجرا می‌کنم، هم کاری می‌کنم زمان discovery از ابتدای پروژه‌ی بعدی در برنامه دیده شود.' },
    ],
  },
  {
    id: 'SC06', kind: 'scenario', competency: 'solution-accountability',
    fa: 'سه ماه از انتشار redesign تو گذشته و متریک هدف تکان نخورده است. چه می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'منتظر می‌مانم تیم تصمیم بگیرد قدم بعدی چیست.' },
      { id: 'b', score: 3, sourceColumn: 'Senior, "Post-Launch Iteration Strategy"',
        fa: 'مالکیت funnel را برمی‌دارم و چند چرخه‌ی build-measure-learn را تا رسیدن به هدف جلو می‌برم.' },
      { id: 'c', score: 4, sourceColumn: 'Staff, "Ecosystem Health"',
        fa: 'بررسی می‌کنم آیا بهینه‌سازی این بخش به بخش دیگری ضربه زده است و تصویر کلی را اصلاح می‌کنم.' },
      { id: 'd', score: 2, sourceColumn: 'Mid-Level, "Performance Monitoring"',
        fa: 'فرضیه‌های اولیه را بازبینی می‌کنم و یک variant تازه پیشنهاد می‌دهم.' },
    ],
  },
  {
    id: 'SC07', kind: 'scenario', competency: 'craftsmanship',
    fa: 'یک هفته تا انتشار مانده و متوجه می‌شوی contrast رنگ اصلی محصول استاندارد دسترس‌پذیری را رد نمی‌کند. چه می‌کنی؟',
    options: [
      { id: 'a', score: 2, sourceColumn: 'Mid-Level, "accessible to diverse users"',
        fa: 'رنگ را در همین صفحه اصلاح می‌کنم تا از استاندارد رد شود.' },
      { id: 'b', score: 4, sourceColumn: 'Staff, "global accessibility frameworks"',
        fa: 'موضوع را به یک بازبینی دسترس‌پذیری در سطح Design System تبدیل می‌کنم و قاعده‌اش را می‌گذارم.' },
      { id: 'c', score: 1, sourceColumn: 'Junior',
        fa: 'موضوع را ثبت می‌کنم تا در نسخه‌ی بعد اصلاح شود.' },
      { id: 'd', score: 3, sourceColumn: 'Senior, "Visual Storytelling & Polish"',
        fa: 'اثر تغییر را روی کل محصول می‌سنجم و یک اصلاح هماهنگ پیشنهاد می‌دهم.' },
    ],
  },
  {
    id: 'SC08', kind: 'scenario', competency: 'system-stewardship',
    fa: 'نصف تیم برای رسیدن به deadline از component های سیستم خارج شده‌اند و فایل‌ها پر از نسخه‌ی detach شده است. چه می‌کنی؟',
    options: [
      { id: 'a', score: 3, sourceColumn: 'Senior, "System Evolution & Governance"',
        fa: 'تصمیم می‌گیرم کدام‌ها استثنا هستند و کدام‌ها باید به سیستم برگردند، و سیستم را بر همان اساس عوض می‌کنم.' },
      { id: 'b', score: 1, sourceColumn: 'Junior, "Component Adoption"',
        fa: 'در فایل خودم همه چیز را با component استاندارد می‌سازم.' },
      { id: 'c', score: 4, sourceColumn: 'Staff "Code-to-Design Synchronization" / Lead "System Adoption & Training"',
        fa: 'قاعده‌ی روشنی می‌گذارم که تیم بداند کِی مجاز است از سیستم خارج شود، و آن را با Engineering هم‌تراز می‌کنم.' },
      { id: 'd', score: 2, sourceColumn: 'Mid-Level, "Component Creation & Docs"',
        fa: 'موارد تکراری را جمع می‌کنم و برایشان component تازه می‌سازم.' },
    ],
  },
  {
    id: 'SC09', kind: 'scenario', competency: 'mentorship',
    fa: 'یک طراح junior سه بار پشت سر هم طرحی آورده که مسئله را حل نمی‌کند و هر بار خودت اصلاحش کرده‌ای. چه می‌کنی؟',
    options: [
      { id: 'a', score: 1, sourceColumn: 'Junior',
        fa: 'این بار هم خودم اصلاح می‌کنم چون deadline نزدیک است.' },
      { id: 'b', score: 4, sourceColumn: 'Staff "Craft Masterclasses" / Lead "Career Pathing"',
        fa: 'می‌بینم این الگو در تیم تکرار می‌شود و با تغییر آیین critique یا آموزش، ریشه‌اش را می‌زنم.' },
      { id: 'c', score: 2, sourceColumn: 'Mid-Level, "Constructive Critique"',
        fa: 'دقیق می‌گویم کجا اشکال دارد و چطور باید اصلاح شود.' },
      { id: 'd', score: 3, sourceColumn: 'Senior, "Direct Mentoring"',
        fa: 'با او می‌نشینم تا خودش تشخیص بدهد کجای تعریف مسئله را جا انداخته است.' },
    ],
  },
  {
    id: 'SC10', kind: 'scenario', competency: 'adaptability',
    fa: 'وسط پروژه، مدیریت اعلام می‌کند اولویت شرکت عوض شده و کار سه هفته‌ی اخیر تیم فعلاً کنار می‌رود. چه می‌کنی؟',
    options: [
      { id: 'a', score: 2, sourceColumn: 'Mid-Level, "Handling Ambiguity"',
        fa: 'می‌پرسم چه بخشی از کار قبلی هنوز قابل استفاده است و همان را نگه می‌دارم.' },
      { id: 'b', score: 4, sourceColumn: 'Lead, "Team Resilience & Safety"',
        fa: 'تصمیم می‌گیرم چه چیزی باید عوض شود و چه چیزی باید ثابت بماند تا تیم دچار whiplash نشود، و این را با تیم شفاف می‌کنم.' },
      { id: 'c', score: 1, sourceColumn: 'Junior, "Task Resilience"',
        fa: 'کار جدید را شروع می‌کنم و منتظر جزئیات بیشتر می‌مانم.' },
      { id: 'd', score: 3, sourceColumn: 'Senior, "Pivot Leadership"',
        fa: 'هزینه‌ی تغییر را شفاف می‌کنم و مسیر جدید را با کم‌ترین دورریز طراحی می‌کنم.' },
    ],
  },
] as const satisfies readonly Question[];
